/* Page-to-page navigation for the compiled Profolio KSA pages.
   Generated by scripts/ds/prototype.mjs — do not edit. The product navigates
   with click handlers, which a static page does not have; this resolves those
   clicks to the compiled pages. States are wired by data-pf-go (compile.mjs). */
(function () {
  var ROUTES = {"/dashboard":"dashboard.html","/listings":"listings.html","/credits-usage":"credits-usage.html","/ad-license":"ad-license.html","/lms/leads":"lms-leads.html","/reports/summary":"reports-summary.html","/reports/listing-report":"reports-listing-report.html","/reports/leads-reports":"reports-leads-reports.html","/user-settings/user-profile":"user-settings-user-profile.html","/user-settings/agency-profile":"user-settings-agency-profile.html","/user-settings/change-password":"user-settings-change-password.html","/agency-staff":"agency-staff.html","/agent-performance":"agent-performance.html","/packages":"packages.html","/post-listing":"post-listing.html","/user-settings/licenses":"user-settings-licenses.html"};
  var MENU = {"all-listings":"/listings","credits_usage":"/credits-usage","leads":"/lms/leads","agent-performance":"/agent-performance","reports":"/reports/summary","agency-staff":"/agency-staff","settings":"/user-settings/user-profile","prop-shop":"/packages","dashboard":"/dashboard","post-listing":"/post-listing","inbox":"/inbox/received","summary":"/reports/summary","listing-reports":"/reports/listing-report","leads-reports":"/reports/leads-reports"};
  var LABELS = {"View All Listings":"/listings","My Listings":"/listings","Credits Usage":"/credits-usage","TruLeads":"/lms/leads","Agent Performance":"/agent-performance","Reports":"/reports/summary","Agency Staff":"/agency-staff","Settings":"/user-settings/user-profile","Credits & Packages":"/packages","Get an Ad License":"/ad-license","User Settings":"/user-settings/user-profile","Licenses":"/user-settings/licenses","Preferences":"/user-settings/preferences","Change Password":"/user-settings/change-password","Agency Settings":"/user-settings/agency-profile"};
  var root = /\/states\/[^/]*$/.test(location.pathname) ? '../' : '';
  function norm(p) {
    p = (p || '').replace(/^https?:\/\/[^/]+/, '').replace(/^\/(en|ar)(?=\/|$)/, '').replace(/[?#].*$/, '').replace(/\/$/, '');
    return p || '/dashboard';
  }
  function toast(msg) {
    var t = document.createElement('div');
    t.textContent = msg;
    t.setAttribute('style', 'position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:2147483647;background:#1f2328;color:#fff;font:13px/1.45 system-ui,-apple-system,sans-serif;padding:10px 14px;border-radius:8px;box-shadow:0 6px 20px rgba(0,0,0,.25);max-width:80vw;pointer-events:none');
    document.body.appendChild(t);
    setTimeout(function () { t.remove(); }, 2800);
  }
  function go(route, label) {
    var r = norm(route), f = ROUTES[r];
    if (f) location.href = root + f;
    else toast((label ? '“' + label + '” — ' : '') + r + ' is not compiled into this prototype yet');
  }
  function text(el) { return (el.getAttribute('aria-label') || el.getAttribute('title') || el.innerText || '').trim().replace(/\s+/g, ' '); }
  document.addEventListener('click', function (e) {
    if (e.defaultPrevented || e.button !== 0) return;
    var t = e.target;
    if (!t || !t.closest) return;
    var a = t.closest('a[href]');
    if (a) {
      var h = a.getAttribute('href');
      if (/^\/(en|ar)?(\/|$)/.test(h)) { e.preventDefault(); go(h, text(a)); }
      return;
    }
    var mi = t.closest('[data-menu-id]');
    if (mi) {
      var m = /^rc-menu-uuid-\d+-\d+-(.+)$/.exec(mi.getAttribute('data-menu-id') || '');
      if (m && MENU[m[1]]) { e.preventDefault(); go(MENU[m[1]], text(mi)); return; }
    }
    for (var el = t, n = 0; el && el !== document.body && n < 6; el = el.parentElement, n++) {
      var l = text(el);
      if (l && LABELS[l]) { e.preventDefault(); go(LABELS[l], l); return; }
      if (el.getBoundingClientRect().width > 420) break;
    }
  }, false);
})();
