#!/usr/bin/env node
/**
 * Write deliverables/prototype.js — page-to-page navigation for the compiled
 * site.
 *
 * WHY: the product navigates with click HANDLERS, not links. A rail item is an
 * <li role="menuitem"> whose onClick calls react-router's navigate(); a
 * settings tab is an <a> with no href. Frozen into static HTML, none of them
 * goes anywhere — the compiled pages looked like the product and could not be
 * walked through like it. compile.mjs already wires every trigger that opens a
 * STATE (data-pf-go); this wires every click that goes to another SCREEN.
 *
 * It is resolved at click time, from three tables, so adding a page never
 * means recompiling the others:
 *
 *   ROUTES   product route → compiled file (scripts/pages-list.mjs ALL)
 *   MENU     a rail item's key (its data-menu-id) → route. Read off the rail
 *            itself, then filled in from the product's own
 *            src/tenant/common/menuList/menuList.js
 *   LABELS   every control harness/explore.mjs clicked and saw CHANGE THE URL
 *            (data/states/*.json links) → where it went. Labels that name
 *            nothing (an icon, a number, a listing's id) are left out.
 *
 * A destination that is not compiled says so in a toast instead of doing
 * nothing, so a reviewer knows it is a gap and not a dead control.
 *
 *   node scripts/ds/prototype.mjs
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ALL } from '../pages-list.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const REPO = join(ROOT, '..', process.env.PROFOLIO_REPO || 'profolio-reactjs');
const norm = (p) => (p || '').replace(/^https?:\/\/[^/]+/, '').replace(/^\/(en|ar)(?=\/|$)/, '').replace(/[?#].*$/, '').replace(/\/$/, '') || '/dashboard';

/* ── ROUTES ─────────────────────────────────────────────────────────────── */
const ROUTES = {};
for (const [slug, route] of Object.entries(ALL)) if (existsSync(join(ROOT, 'deliverables', `${slug}.html`))) ROUTES[route] = `${slug}.html`;

/* ── LABELS, from what the explorer saw navigate ──────────────────────── */
const LABELS = {};
const GENERIC = /^(icon|svg|div|span|img|button|a|li|p|x|i|\d+|[\W_]+)$/i;
for (const f of readdirSync(join(ROOT, 'data', 'states')).filter((f) => f.endsWith('.json'))) {
  for (const l of JSON.parse(readFileSync(join(ROOT, 'data', 'states', f), 'utf8')).links || []) {
    const label = (l.label || '').trim();
    if (!label || GENERIC.test(label) || label.length > 32 || /[?]preview=/.test(l.to) || /^\/ar\//.test(l.to)) continue;
    if (/\?/.test(l.to)) continue;                               /* a query is a state of the same page, not a screen */
    LABELS[label] ||= norm(l.to);
  }
}

/* ── MENU, from the rail and the product's own menu list ─────────────── */
const MENU = {};
const dash = join(ROOT, 'deliverables', 'dashboard.html');
if (existsSync(dash)) {
  const html = readFileSync(dash, 'utf8');
  for (const m of html.matchAll(/<li[^>]*title="([^"]*)"[^>]*data-menu-id="rc-menu-uuid-\d+-\d+-([^"]+)"/g)) {
    const title = m[1].replace(/&amp;/g, '&'), key = m[2];
    if (LABELS[title]) MENU[key] = LABELS[title];
  }
}
const menuList = join(REPO, 'src', 'tenant', 'common', 'menuList', 'menuList.js');
if (existsSync(menuList)) {
  const src = readFileSync(menuList, 'utf8');
  /* a key and the first path that follows it inside the same entry (top-level
     entries declare key first), or a path followed by its key (the children) */
  for (const m of src.matchAll(/key:\s*'([^']+)'[\s\S]{0,400}?path:\s*'([^']+)'/g)) MENU[m[1]] ||= m[2];
  for (const m of src.matchAll(/path:\s*'([^']+)',\s*key:\s*'([^']+)'/g)) MENU[m[2]] = m[1];
}

/* ── the script ────────────────────────────────────────────────────────── */
const js = `/* Page-to-page navigation for the compiled Profolio KSA pages.
   Generated by scripts/ds/prototype.mjs — do not edit. The product navigates
   with click handlers, which a static page does not have; this resolves those
   clicks to the compiled pages. States are wired by data-pf-go (compile.mjs). */
(function () {
  var ROUTES = ${JSON.stringify(ROUTES)};
  var MENU = ${JSON.stringify(MENU)};
  var LABELS = ${JSON.stringify(LABELS)};
  var root = /\\/states\\/[^/]*$/.test(location.pathname) ? '../' : '';
  function norm(p) {
    p = (p || '').replace(/^https?:\\/\\/[^/]+/, '').replace(/^\\/(en|ar)(?=\\/|$)/, '').replace(/[?#].*$/, '').replace(/\\/$/, '');
    return p || '/dashboard';
  }
  function toast(msg) {
    var t = document.createElement('div');
    t.textContent = msg;
    t.setAttribute('style', 'position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:2147483647;background:#1f2328;color:#fff;font:13px/1.45 system-ui,-apple-system,sans-serif;padding:10px 14px;border-radius:8px;box-shadow:0 6px 20px rgba(0,0,0,.25);max-width:80vw;pointer-events:none');
    document.body.appendChild(t);
    setTimeout(function () { t.remove(); }, 2800);
  }
  function go(route, label) {
    var r = norm(route), f = ROUTES[r];
    if (f) location.href = root + f;
    else toast((label ? '“' + label + '” — ' : '') + r + ' is not compiled into this prototype yet');
  }
  function text(el) { return (el.getAttribute('aria-label') || el.getAttribute('title') || el.innerText || '').trim().replace(/\\s+/g, ' '); }
  document.addEventListener('click', function (e) {
    if (e.defaultPrevented || e.button !== 0) return;
    var t = e.target;
    if (!t || !t.closest) return;
    var a = t.closest('a[href]');
    if (a) {
      var h = a.getAttribute('href');
      if (/^\\/(en|ar)?(\\/|$)/.test(h)) { e.preventDefault(); go(h, text(a)); }
      return;
    }
    var mi = t.closest('[data-menu-id]');
    if (mi) {
      var m = /^rc-menu-uuid-\\d+-\\d+-(.+)$/.exec(mi.getAttribute('data-menu-id') || '');
      if (m && MENU[m[1]]) { e.preventDefault(); go(MENU[m[1]], text(mi)); return; }
    }
    for (var el = t, n = 0; el && el !== document.body && n < 6; el = el.parentElement, n++) {
      var l = text(el);
      if (l && LABELS[l]) { e.preventDefault(); go(LABELS[l], l); return; }
      if (el.getBoundingClientRect().width > 420) break;
    }
  }, false);
})();
`;
writeFileSync(join(ROOT, 'deliverables', 'prototype.js'), js);
console.log(`  deliverables/prototype.js — ${Object.keys(ROUTES).length} compiled routes · ${Object.keys(MENU).length} rail keys · ${Object.keys(LABELS).length} labelled links`);
console.log('  rail:', Object.entries(MENU).map(([k, v]) => `${k}→${v}${ROUTES[v] ? '' : ' (not compiled)'}`).join('  '));
